ALTER TABLE USERAPP
    ADD CONSTRAINT pk_Userapp PRIMARY KEY (username)
    USING INDEX
    TABLESPACE US_Ind PCTFREE 20
    STORAGE (INITIAL 10k NEXT 10k PCTINCREASE 0);

ALTER TABLE USERTYPE
    ADD CONSTRAINT pk_UserType PRIMARY KEY (id_usertype)
    USING INDEX
    TABLESPACE US_Ind PCTFREE 20
    STORAGE (INITIAL 10k NEXT 10k PCTINCREASE 0);

ALTER TABLE BANREASON
    ADD CONSTRAINT pk_BanReason PRIMARY KEY (id_banreason)
    USING INDEX
    TABLESPACE US_Ind PCTFREE 20
    STORAGE (INITIAL 10k NEXT 10k PCTINCREASE 0);

ALTER TABLE BANREASONXUSERAPP
    ADD CONSTRAINT pk_BanReasonXUserapp PRIMARY KEY (id_banreason, username)
    USING INDEX
    TABLESPACE US_Ind PCTFREE 20
    STORAGE (INITIAL 10k NEXT 10k PCTINCREASE 0);