ALTER TABLE TRANSCRIPT
    ADD CONSTRAINT pk_Transcript PRIMARY KEY (transcript_number)
    USING INDEX
    TABLESPACE TR_Ind PCTFREE 20
    STORAGE (INITIAL 10k next 10k PCTINCREASE 0);

ALTER TABLE TRANSCRIPTTYPE
    ADD CONSTRAINT pk_TranscriptType PRIMARY KEY (id_transcripttype)
    USING INDEX
    TABLESPACE TR_Ind PCTFREE 20
    STORAGE (INITIAL 10k next 10k PCTINCREASE 0);

ALTER TABLE ACCUSED
    ADD CONSTRAINT pk_Accused PRIMARY KEY (id_accused)
    USING INDEX
    TABLESPACE TR_Ind PCTFREE 20
    STORAGE (INITIAL 10k next 10k PCTINCREASE 0);

ALTER TABLE VERDICT
    ADD CONSTRAINT pk_Verdict PRIMARY KEY (id_verdict)
    USING INDEX
    TABLESPACE TR_Ind PCTFREE 20
    STORAGE (INITIAL 10k next 10k PCTINCREASE 0);

ALTER TABLE SENTENCE
    ADD CONSTRAINT pk_Sentence PRIMARY KEY (id_sentence)
    USING INDEX
    TABLESPACE TR_Ind PCTFREE 20
    STORAGE (INITIAL 10k next 10k PCTINCREASE 0);

ALTER TABLE SENTENCETYPE
    ADD CONSTRAINT pk_SentenceType PRIMARY KEY (id_sentencetype)
    USING INDEX
    TABLESPACE TR_Ind PCTFREE 20
    STORAGE (INITIAL 10k next 10k PCTINCREASE 0);

ALTER TABLE CRIME
    ADD CONSTRAINT pk_Crime PRIMARY KEY (id_crime)
    USING INDEX
    TABLESPACE TR_Ind PCTFREE 20
    STORAGE (INITIAL 10k next 10k PCTINCREASE 0);

ALTER TABLE PHOTO
    ADD CONSTRAINT pk_Photo PRIMARY KEY (id_photo)
    USING INDEX
    TABLESPACE TR_Ind PCTFREE 20
    STORAGE (INITIAL 10k next 10k PCTINCREASE 0);