ALTER TABLE PERSON
    ADD CONSTRAINT pk_Person PRIMARY KEY (id_person)
    USING INDEX
    TABLESPACE PRSN_Ind PCTFREE 20
    STORAGE (INITIAL 10k NEXT 10k PCTINCREASE 0);

ALTER TABLE COMPANY
    ADD CONSTRAINT pk_Company PRIMARY KEY (id_company)
    USING INDEX
    TABLESPACE PRSN_Ind PCTFREE 20
    STORAGE (INITIAL 10k NEXT 10k PCTINCREASE 0);

ALTER TABLE GENDER
    ADD CONSTRAINT pk_Gender PRIMARY KEY (id_gender)
    USING INDEX
    TABLESPACE PRSN_Ind PCTFREE 20
    STORAGE (INITIAL 10k NEXT 10k PCTINCREASE 0);