ALTER TABLE GENERALLOG
    ADD CONSTRAINT pk_GeneralLog PRIMARY KEY (id_generallog)
    USING INDEX
    TABLESPACE ADM_Ind PCTFREE 20
    STORAGE (INITIAL 10k NEXT 10k PCTINCREASE 0);

ALTER TABLE PARAMETER_TABLE
    ADD CONSTRAINT pk_Parameter PRIMARY KEY (id_parameter)
    USING INDEX
    TABLESPACE ADM_Ind PCTFREE 20
    STORAGE (INITIAL 10k NEXT 10k PCTINCREASE 0);