CREATE TABLESPACE ADM_Data
    DATAFILE 'C:\app\Familia\oradata\DBPRUEBA\admData01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON
    NEXT 512K
    MAXSIZE 200M;
	
CREATE TABLESPACE ADM_Ind
    DATAFILE 'C:\app\Familia\oradata\DBPRUEBA\admInd01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON
    NEXT 512K
    MAXSIZE 200M;
    
CREATE USER ADM
    IDENTIFIED BY ADM
    DEFAULT TABLESPACE ADM_Data
    QUOTA 10M ON ADM_Data
    TEMPORARY TABLESPACE temp
    QUOTA 5M ON system ;
    
GRANT CONNECT TO ADM;

GRANT CREATE SESSION TO ADM;

GRANT CREATE TABLE TO ADM;

GRANT UNLIMITED TABLESPACE TO ADM;

GRANT CREATE TRIGGER TO ADM;